name: GetRepositoryName
on:
  workflow_dispatch:

jobs:
  getreponame:
    name: getreponame
    runs-on: ubuntu-latest
    steps:
      - run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_ENV
      
      - run: echo ${{ env.REPOSITORY_NAME }}

      
