name: GetRepositoryName
on:
  workflow_dispatch:

jobs:
  getreponame:
    name: getreponame
    runs-on: ubuntu-latest
    steps:
      - name: GetRepositoryName
        run: echo "/home/${REPOSITORY_NAME}"
        env:
          REPOSTIROY_NAME:  ${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}
      
      

      
